#!/usr/bin/env bash

# Variables
set -e
export WORKDIR=$(cd $(dirname $0) && pwd)
# shellcheck source=common
. "$WORKDIR/common"

# Colors
BLACK='\033[0;30m'
RED='\033[0;31m'
GREEN='\033[0;32m'
ORANGE='\033[0;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
LIGHT_GRAY='\033[0;37m'
DARK_GRAY='\033[1;30m'
LIGHT_RED='\033[1;31m'
LIGHT_GREEN='\033[1;32m'
LIGHT_YELLOW='\033[1;33m'
LIGHT_BLUE='\033[1;34m'
LIGHT_PURPLE='\033[1;35m'
LIGHT_CYAN='\033[1;36m'
WHITE='\033[1;37m'
NC='\033[0m' # No Color

DESTINATION=/usr/local/bin/bmcli

# Helper
asExecutable() {
  cp $WORKDIR/bmcli $DESTINATION
}

update() {
  rm "/usr/local/bin/bmcli"
  cp $WORKDIR/bmcli $DESTINATION
}

cli_help() {
  cli_name=${0##*/}
  echo "
$cli_name
Beast Mode CLI
Version: $(cat $WORKDIR/VERSION)
https://github.com/ShadyDL/bmcli

Usage: $cli_name [command]

Commands:
  start_day        Start applications
  go_home          Stop workflow applications

  update           Run this when you changed the src code
  as_executable    Run this with ./bmcli to copy to script to your path
  *                Help
"
  exit 1
}

# CLI Commands
startDay() {
  cli_help_start_flow() {
    echo "
Command: Start flow

Usage: 
  start_flow"
    exit 1
  }

  # Main
  export BAGCLI_PROJECT_NAME=$1
  echo
  echo -e "${LIGHT_YELLOW}Another day, another... ahh whatevs get me some coffee...${NC}"
  echo "Loading..."

  apps=(
    "Slack"
    "Google Chrome"
    "Arc"
    "Spotify"
    "1Password"
    "NordPass"
    "Calendar"
    "Visual Studio Code"
  )

  for i in ${!apps[@]}; do
    appName="\"${apps[$i]}\""
    cmd="launch app ${appName}"
    sudo osascript -e "$cmd"
  done

  echo
  echo -e "${GREEN} All set up! Enjoy your coffee☕ and sigaret 🚬 ${NC}"
  echo
}

goHome() {
  echo -e "${LIGHT_YELLOW} Quiting already??! ${NC}"

  apps=(
    "Slack"
    "Google Chrome"
    "Arc"
    "Music"
    "Spotify"
    "1Password"
    "NordPass"
    "Calendar"
    "Finder"
    "Visual Studio Code"
  )

  for i in ${!apps[@]}; do
    appName="\"${apps[$i]}\""
    cmd="quit app ${appName}"
    sudo osascript -e "$cmd"
  done

  echo -e "${GREEN} Guess we're done here, leggo gtfo! ${NC}"
  echo ''
  echo ''

}

# Main

# cli_log "Exporting config ..."
# [ ! -f "$WORKDIR/config" ] \
#   && echo "ERROR: No $WORKDIR/config file found. " \
#   && echo "cp $WORKDIR/config.template $WORKDIR/config and adjust." \
#   && exit 1

# export $(cat "$WORKDIR/config" | xargs)

case "$1" in
deploy | d)
  "$WORKDIR/commands/deploy" "$2"
  ;;

start_day)
  startDay
  # "$WORKDIR/commands/start_day" | tee -ia "$WORKDIR/logs/deploy_${2}.log" # Deprecated, cannot run folder as single executable
  ;;

go_home)
  goHome
  ;;

update)
  update
  ;;

as_executable)
  asExecutable
  ;;
*)

  cli_help
  ;;
esac
