#!/usr/bin/env bash

# set -e
# . "$WORKDIR/common"

YELLOW='\033[1;33m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

cli_help_start_flow() {
  echo "
Command: Start flow

Usage: 
  start_flow"
  exit 1
}

export BAGCLI_PROJECT_NAME=$1
echo
echo -e "${YELLOW}Another day, another... ahh whatevs get me some coffee...${YELLOW}"
echo "Loading..."

apps=(
"Slack"
"Google Chrome"
"Arc"
"Spotify"
"1Password"
"NordPass"
"Calendar"
"Visual Studio Code"
)

for i in ${!apps[@]}; do
  appName="\"${apps[$i]}\""
  cmd="launch app ${appName}"
  sudo osascript -e "$cmd"
done

echo
echo -e "${GREEN} All set up! Enjoy your coffee☕ and sigaret 🚬 ${GREEN}"
echo